export enum ValidationErrorCodes {
	USERNAME_REQUIRED = 'VALIDATION_ERROR_USERNAME_REQUIRED',
	USERNAME_INVALID = 'VALIDATION_ERROR_USERNAME_INVALID',
	PASSWORD_REQUIRED = 'VALIDATION_ERROR_PASSWORD_REQUIRED',
	PASSWORD_TOO_SHORT = 'VALIDATION_ERROR_PASSWORD_TOO_SHORT',
	PASSWORD_TOO_WEAK = 'VALIDATION_ERROR_PASSWORD_TOO_WEAK',
	EMAIL_REQUIRED = 'VALIDATION_ERROR_EMAIL_REQUIRED',
	NAME_REQUIRED = 'VALIDATION_ERROR_NAME_REQUIRED',
	TITLE_REQUIRED = 'VALIDATION_ERROR_TITLE_REQUIRED',
	CONTENT_REQUIRED = 'VALIDATION_ERROR_CONTENT_REQUIRED',
	TITLE_TOO_LONG = 'VALIDATION_ERROR_TITLE_TOO_LONG',
	CONTENT_TOO_LONG = 'VALIDATION_ERROR_CONTENT_TOO_LONG'
}

export enum AuthenticationErrorCodes {
	USER_NOT_FOUND = 'AUTH_ERROR_USER_NOT_FOUND',
	INVALID_CREDENTIALS = 'AUTH_ERROR_INVALID_CREDENTIALS',
	ACCOUNT_LOCKED = 'AUTH_ERROR_ACCOUNT_LOCKED',
	ACCOUNT_DISABLED = 'AUTH_ERROR_ACCOUNT_DISABLED',
	LOGIN_REQUIRED = 'AUTH_ERROR_LOGIN_REQUIRED',
	INVALID_TOKEN = 'AUTH_ERROR_INVALID_TOKEN',
	TOKEN_EXPIRED = 'AUTH_ERROR_TOKEN_EXPIRED',
	NO_PERMISSION = 'AUTH_ERROR_NO_PERMISSION'
}

export enum DuplicationErrorCodes {
	EMAIL_EXISTS = 'DUPLICATION_ERROR_EMAIL_EXISTS',
	USERNAME_EXISTS = 'DUPLICATION_ERROR_USERNAME_EXISTS'
}

export enum ServerErrorCodes {
	INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
	SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
	DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR'
}

export type ApiErrorCode =
	| ValidationErrorCodes
	| AuthenticationErrorCodes
	| ServerErrorCodes
	| DuplicationErrorCodes;
